### ISSUE TITLE
Other fish should be steamed.

### ISSUE THREAD

**Issue by xbony2** [Esteemed-Innovation/Flaxbeards-Steam-Power#141]
The salmon(http://minecraft.gamepedia.com/Raw_Salmon) added in 1.7 should be able to be cooked with steam furnace.

**Comment by elifoster** [comment]
@xbony2 I tried to make this work. I get the salmon smelting into the correct item, but the problem is, for some reason, assets just don't effect it. 
1. It does not have a localized name, even though I have set a localized name for it.
2. It uses the Cooked Fish texture, even though I specifically tell it to use the Cooked Salmon texture.

I'll create a branch so you can take a look.

**Comment by xbony2** [comment]
That is weird...
