### ISSUE TITLE
Flash Boiler Heat Countdown

### ISSUE THREAD

**Issue by CrimsonCrystal** [Esteemed-Innovation/Flaxbeards-Steam-Power#272]
The heat countdown (or fuel left, whatever it's called) does not show up in the Flash Boiler. I'm using Flaxbeard'sSteamPower-1.7.10-0.28.7 version.
To replicate:
1. Build a Flash Boiler
2. Put some water in it (I used two aqueous accumulators and two water source blocks in a checkered pattern, if that helps)
3. Put some fuel in (I used lava bucket)
You'll see that the fuel left indicator stays at max for the entire duration, and then suddenly plummets as the fuel runs out.

Developer edit:

* [x] Boiler issues
  * [x] Heat countdown resets and stays the same if you exit the GUI
  * [x] Heat countdown will stay at the bottom if you put another fuel in it when it is complete
* [x] Flash Boiler issues
  * [ ] Heat countdown does not update until it is finished smelting
   * Not even if you exit the GUI and come back into it

**Comment by elifoster** [comment]
I have confirmed this with fuel other than lava buckets.

**Comment by elifoster** [comment]
This actually happens with the normal Boiler too, just differently slightly. I haven't tested these with the Flash Boiler, but I imagine they are similar, since the two machines use the same Containers.

* Heat countdown resets and stays the same if you exit the GUI
* Heat countdown works perfectly if you stay in the GUI until it ends
* Heat countdown will stay at the bottom if you put another fuel in it when it is complete
