### ISSUE TITLE
What are Mod Scope Constraints in relation to Minecraft Physics

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#331]
I have a small pile of ideas/requests to make, but before doing so I'd like to get clarification on the scope / theme of the mod.

I understand there is a desire for verisimilitude (or realism), but how much of that is focused on real world examples vs vanilla minecraft physics/lore?

For example:
IRL you can't put steam in capsules and get it out usefully later, because the metal shell would conduct the heat outward and the water would condense. But in minecraft all the heat you need for percolation for all the potions ever is provided by a single blaze rod's unending heat. Couldn't a metal capsule with blaze powder within it wrapped in wool, at least replenish enough of the lost heat to keep steam actively volatile?

**Comment by elifoster** [comment]
I'd say it's a balance of MC, real-life, and goofiness.

Probably my favorite example of this balance is the Rocket Launcher. It's an item based on a real-life thing, using Minecraft physics for its effects, while also allowing Rocket Jumping for goofiness.

Many of the items fit only one or two of those themes (MC, real-life, and goofiness), but since they are all covered equally, it creates balance over the whole mod.

**Comment by Divineaspect** [comment]
As per IRC conversation
"As per Tamriel's Dwemer, rather then steampunk."
