### ISSUE TITLE
[intra-mod compat] Steam Drill not mining at correct levels

### ISSUE THREAD

**Issue by ParadoxBomb** [Esteemed-Innovation/Flaxbeards-Steam-Power#398]
## Description
When used with Tinkers' Construct, the Steam Drill seems to become unable to mine Obsidian due to the way that Tinkers' Construct changes harvest levels. This further breaks when Iguana's Tinker Tweaks is installed and the Harvest Level tweaks are enabled, as it seems to think that the steam drill is locked to Tin (iron) mining level, no matter the head or what custom values are added in FSP-materials.json.
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Flaxbeard's Steam Power version: 1.7.10-0.29.1

**Comment by elifoster** [comment]
The Steam Drill can't mine Obsidian unless you have a level 3 drill head installed (by default, only emerald and diamond provide this). I have TiCo installed in my dev environment and with a level 3 head, I'm able to mine obsidian.

I don't know what the harvest level tweaks do and I haven't played with Iguana Tweaks since I was playtesting FTB Monster before its release, so I can't really speak on that...

**Comment by ParadoxBomb** [comment]
Well now I feel silly. After some further testing, it seems that I was jumping to conclusions based on the WAILA Habitability tooltip improperly showing the drill being unable to mine obsidian. When a diamond head is applied to the tool, it functions properly, as does the manyullin drill head that I json'd in. My most sincere apologies.

**Comment by elifoster** [comment]
No need to apologize :smile:
