### ISSUE TITLE
Copper/ Zinc Oregen Disabled/Not working in 1.0 Alpha

### ISSUE THREAD

**Issue by OrcAndHat** [Esteemed-Innovation/Flaxbeards-Steam-Power#480]
## Copper and Zinc Ore are not spawning in the Overworld or the Nether. 

Neither Copper nor Zinc blocks are spawning in Taiga biomes, nor in the Nether. I looked at the config, which suggested that Copper was only supposed to spawn in Extreme Hills biomes and checked there as well, only to find no copper ore.

I checked the Nether which was supposed to have Copper and Zinc ore and I found no sign of either. I did not yet check the End, or the Desert and Mesa biomes that according to the Config spawn Zinc ore.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:12.18.3.2254
* Esteemed Innovation version:1.10 1.0 Alpha 11 Fa7aa1

**Comment by elifoster** [comment]
What Y level were you checking? Copper generates in the biomes specified in the config between Y80 and Y128, while Zinc generates between Y65 and Y80.

Now that I think of it, it might be better to set that to be configurable as well, maybe even on a per-biome basis, because some biomes are taller/shorter than others.

**Comment by OrcAndHat** [comment]
I was checking below Y80, which was the source for the copper problem. I found copper when I started checking above that level.

**Comment by OrcAndHat** [comment]
Yeah, this one should be closed/invalid. I was just looking at the wrong Z-levels.
